package com.sybbox.ui.settings

import com.sybbox.R

data class SettingsEntry(
    val titleRes: Int,
    val summaryRes: Int?,
    val section: SettingsSection,
)

val settingsIndex: List<SettingsEntry> = listOf(
    SettingsEntry(R.string.language, null, SettingsSection.APPEARANCE),
    SettingsEntry(R.string.theme, null, SettingsSection.APPEARANCE),
    SettingsEntry(R.string.dynamic_color, R.string.dynamic_color_summary, SettingsSection.APPEARANCE),
    SettingsEntry(R.string.tcp_fast_open, R.string.tcp_fast_open_summary, SettingsSection.CONNECTION),
    SettingsEntry(R.string.auto_connect_boot, R.string.auto_connect_boot_summary, SettingsSection.CONNECTION),
    SettingsEntry(R.string.connection_timeout, null, SettingsSection.CONNECTION),
    SettingsEntry(R.string.auto_failover, R.string.auto_failover_summary, SettingsSection.CONNECTION),
    SettingsEntry(R.string.resolve_server, R.string.resolve_server_summary, SettingsSection.CONNECTION),
    SettingsEntry(R.string.always_on_vpn, R.string.always_on_vpn_summary, SettingsSection.CONNECTION),
    SettingsEntry(R.string.routing_mode, null, SettingsSection.ROUTING),
    SettingsEntry(R.string.bypass_local, R.string.bypass_local_summary, SettingsSection.ROUTING),
    SettingsEntry(R.string.block_ads, R.string.block_ads_summary, SettingsSection.ROUTING),
    SettingsEntry(R.string.block_trackers, R.string.block_trackers_summary, SettingsSection.ROUTING),
    SettingsEntry(R.string.remote_dns, R.string.remote_dns_summary, SettingsSection.DNS),
    SettingsEntry(R.string.direct_dns, R.string.direct_dns_summary, SettingsSection.DNS),
    SettingsEntry(R.string.dns_strategy, null, SettingsSection.DNS),
    SettingsEntry(R.string.fake_ip, R.string.fake_ip_summary, SettingsSection.DNS),
    SettingsEntry(R.string.fake_ip_range, null, SettingsSection.DNS),
    SettingsEntry(R.string.custom_sni, R.string.custom_sni_summary, SettingsSection.TRANSPORT),
    SettingsEntry(R.string.tls_fragment, R.string.tls_fragment_summary, SettingsSection.TRANSPORT),
    SettingsEntry(R.string.fragment_delay, null, SettingsSection.TRANSPORT),
    SettingsEntry(R.string.record_fragment, R.string.record_fragment_summary, SettingsSection.TRANSPORT),
    SettingsEntry(R.string.multiplex, R.string.multiplex_summary, SettingsSection.TRANSPORT),
    SettingsEntry(R.string.mux_protocol, null, SettingsSection.TRANSPORT),
    SettingsEntry(R.string.mux_max_streams, null, SettingsSection.TRANSPORT),
    SettingsEntry(R.string.mux_padding, R.string.mux_padding_summary, SettingsSection.TRANSPORT),
    SettingsEntry(R.string.tun_stack, null, SettingsSection.TUNNEL),
    SettingsEntry(R.string.tun_mtu, null, SettingsSection.TUNNEL),
    SettingsEntry(R.string.auto_route, R.string.auto_route_summary, SettingsSection.TUNNEL),
    SettingsEntry(R.string.strict_route, R.string.strict_route_summary, SettingsSection.TUNNEL),
    SettingsEntry(R.string.leak_protection, R.string.leak_protection_summary, SettingsSection.TUNNEL),
    SettingsEntry(R.string.hide_tunnel_address, R.string.hide_tunnel_address_summary, SettingsSection.TUNNEL),
    SettingsEntry(R.string.block_webrtc, R.string.block_webrtc_summary, SettingsSection.TUNNEL),
    SettingsEntry(R.string.local_proxy, R.string.local_proxy_summary, SettingsSection.LOCAL_PROXY),
    SettingsEntry(R.string.local_proxy_port, null, SettingsSection.LOCAL_PROXY),
    SettingsEntry(R.string.proxy_user, R.string.proxy_auth_summary, SettingsSection.LOCAL_PROXY),
    SettingsEntry(R.string.proxy_password, null, SettingsSection.LOCAL_PROXY),
    SettingsEntry(R.string.allow_lan, R.string.allow_lan_summary, SettingsSection.LOCAL_PROXY),
    SettingsEntry(R.string.update_on_start, null, SettingsSection.STARTUP),
    SettingsEntry(R.string.connect_on_start, R.string.connect_on_start_summary, SettingsSection.STARTUP),
    SettingsEntry(R.string.sub_auto_update, R.string.sub_auto_update_summary, SettingsSection.SUBSCRIPTIONS),
    SettingsEntry(R.string.sub_interval, R.string.sub_interval_summary, SettingsSection.SUBSCRIPTIONS),
    SettingsEntry(R.string.sub_update_notify, R.string.sub_update_notify_summary, SettingsSection.SUBSCRIPTIONS),
    SettingsEntry(R.string.tunnel_check, R.string.tunnel_check_summary, SettingsSection.DIAGNOSTICS),
    SettingsEntry(R.string.probe_url, R.string.probe_url_summary, SettingsSection.DIAGNOSTICS),
    SettingsEntry(R.string.ping_timeout, null, SettingsSection.DIAGNOSTICS),
    SettingsEntry(R.string.log_limit, R.string.log_limit_summary, SettingsSection.DIAGNOSTICS),
    SettingsEntry(R.string.log_level, R.string.log_level_summary, SettingsSection.DIAGNOSTICS),
    SettingsEntry(R.string.check_update, null, SettingsSection.MAINTENANCE),
    SettingsEntry(R.string.auto_update_check, R.string.auto_update_check_summary, SettingsSection.MAINTENANCE),
    SettingsEntry(R.string.reset_settings, R.string.reset_settings_summary, SettingsSection.MAINTENANCE),
    SettingsEntry(R.string.app_version, null, SettingsSection.ABOUT),
    SettingsEntry(R.string.android_version, null, SettingsSection.ABOUT),
    SettingsEntry(R.string.device_model, null, SettingsSection.ABOUT),
    SettingsEntry(R.string.hwid, null, SettingsSection.ABOUT),
    SettingsEntry(R.string.source_code, null, SettingsSection.ABOUT),
)
